name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure global git auth
        run: git config --global http.https://github.com/.extraheader "$(git config --local http.https://github.com/.extraheader)"

      - name: Build
        run: ./script/build.sh

      - name: Verify no unstaged changes
        run: ./script/verify-no-unstaged-changes.sh

      - name: Test tarball
        run: ./script/test.sh ./_layout/action_versions.tar.gz
      
      - name: Test zipball
        run: ./script/test.sh ./_layout/action_versions.zip

      - name: Release
        if: github.event_name == 'workflow_dispatch'
        run: |
          gh release create v${{github.sha}} --generate-notes ./_layout/action_versions.zip ./_layout/action_versions.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
